export const PAKISTAN_CITIES = [
  'Karachi',
  'Lahore',
  'Faisalabad',
  'Rawalpindi',
  'Gujranwala',
  'Peshawar',
  'Multan',
  'Hyderabad',
  'Islamabad',
  'Quetta',
  'Bahawalpur',
  'Sargodha',
  'Sialkot',
  'Sukkur',
  'Larkana',
  'Shekhupura',
  'Jhang',
  'Gujrat',
  'Mardan',
  'Kasur',
  'Rahim Yar Khan',
  'Sahiwal',
  'Okara',
  'Wah Cantonment',
  'Dera Ghazi Khan',
  'Mirpur Khas',
  'Nawabshah',
  'Chiniot',
  'Kamoke',
  'Sadiqabad',
  'Turbat',
  'Shikarpur',
  'Khairpur',
  'Hafizabad',
  'Kohat',
  'Khanewal',
  'Dera Ismail Khan',
  'Muzaffargarh',
  'Mandi Bahauddin',
  'Abbottabad',
  'Hub',
  'Daska',
  'Gojra',
  'Dadu',
  'Muridke',
  'Bahawalnagar',
  'Samundri',
  'Tando Allahyar',
  'Tando Adam',
  'Jaranwala',
  'Chishtian',
  'Attock',
  'Vehari',
  'Kot Abdul Malik',
  'Ferozwala',
  'Gwadar',
  'Bhimber',
  'Muzaffarabad',
  'Kotli',
  'Mirpur',
  'Skardu',
  'Gilgit'
];
